name: Build & Test

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build tests
        run: |
          gcc main.c libs/files/lib_file_manager.c libs/logs/lib_logs_manager.c libs/strings/lib_strings_manager.c libs/tests/lib_tests_manager.c tests/files.test.c tests/strings.test.c -o main.exe

      - name: Run tests
        run: ./main.exe
